blank_issues_enabled: false
contact_links:
  - name: Contributing to requests-pprint
    url: https://github.com/YisusChrist/requests-pprint/blob/main/CONTRIBUTING.md
    about: Guidelines for how to report an issue.
  - name: Support
    url: https://github.com/YisusChrist/requests-pprint/discussions
    about: Ask the community for support
  - name: Documentation
    url: https://github.com/YisusChrist/requests-pprint/wiki
    about: Many questions might be already answered here.
